/**
 * The cruise catalogue, read from D1 at request time.
 *
 * This replaces src/data/cruise-export.json and scripts/export-cruises.ts in
 * holiday-admin-api. That file was regenerated by deploy.sh, so an offer built
 * in the admin did not exist on the site until someone deployed — and only a
 * developer can deploy. Everything below is the same derivation, moved to
 * where the request is.
 *
 * Shape is unchanged: this returns exactly the RawCruise[] the JSON held, so
 * transformCruise and every page above it are untouched.
 *
 * Cost control. The naive read is 11k cabin rows; the reductions that matter
 * (cheapest cabin per sailing, ships per offer) are done in SQL instead, which
 * brings it to about 3.9k, and the whole catalogue is memoised per isolate for
 * a minute. A listing page therefore does no database work at all on the common
 * path, and a newly built offer appears within a minute without a deploy.
 */
import { sql } from 'drizzle-orm';
import type { Database } from './db';
import type { RawCruise, RawCruiseHotel, RawCruiseShip, RawCruiseItinerary } from './holiday-transforms';

/** holiday-site cruise ids are the D1 offer id plus this offset. */
const ID_OFFSET = 10000;

/** How long a read of the catalogue is reused. The admin's visible lag. */
const TTL_MS = 60_000;

// ── Row shapes ──────────────────────────────────────────────────────

interface ItineraryEntry {
  dayNumber: number;
  portName: string | null;
  country: string | null;
  description: string;
}

interface GalleryImage {
  url: string;
}

interface ShipFacts {
  capacity?: number | null;
  cabin_count?: number | null;
  deck_count?: number | null;
  launch_year?: string | null;
  refit_year?: string | null;
}

interface ShipRawData {
  accomodation_types?: Array<{ images: Array<{ href: string }> }>;
  ship_facts?: ShipFacts;
}

interface ShipDetail {
  name: string;
  description: string;
  coverImage: string;
  class: string;
  rawData: ShipRawData | null;
}

// ── Pure helpers ────────────────────────────────────────────────────

function safeJsonParse(val: unknown): any {
  if (val === null || val === undefined) return null;
  if (typeof val === 'object') return val; // D1 JSON columns arrive parsed
  if (typeof val !== 'string') return null;
  try { return JSON.parse(val); } catch { return null; }
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();
}

/** Round to the closest price point ending in 19, 29, 39, 49, 69, 79, 89, or 99. */
function roundToNine(n: number): number {
  const base = Math.floor(n / 100) * 100;
  const targets = [base + 19, base + 29, base + 39, base + 49, base + 59, base + 69, base + 79, base + 89, base + 99];
  let closest = targets[0];
  let minDist = Math.abs(n - closest);
  for (let i = 1; i < targets.length; i++) {
    const dist = Math.abs(n - targets[i]);
    if (dist < minDist) { closest = targets[i]; minDist = dist; }
  }
  return Math.max(0, closest);
}

function buildShipExport(
  shipId: number,
  detail: ShipDetail,
  firstSailingDate?: string,
  sailingCount?: number,
): RawCruiseShip {
  const accomTypes = detail.rawData?.accomodation_types || [];
  const facts = detail.rawData?.ship_facts;
  const cabinImages: string[] = [];
  const seen = new Set<string>();
  for (const accom of accomTypes) {
    if (accom.images?.length > 0) {
      let href = accom.images[0].href;
      if (href?.startsWith('//')) href = `https:${href}`; // Widgety URLs are protocol-relative
      if (href && !seen.has(href)) { seen.add(href); cabinImages.push(href); }
    }
  }
  return {
    shipId,
    name: detail.name,
    description: detail.description,
    cover_image: detail.coverImage,
    class: detail.class,
    cabin_images: cabinImages,
    facts: {
      capacity: facts?.capacity ?? null,
      cabins: facts?.cabin_count ?? null,
      decks: facts?.deck_count ?? null,
      built: facts?.launch_year ?? null,
      refurbished: facts?.refit_year ?? null,
    },
    firstSailingDate,
    sailingCount,
  };
}

/**
 * The offer's hotel nights, in travel order.
 *
 * A stay only appears with BOTH nights and a hotel name: the page renders it as
 * a named card, and "1 night at (blank)" is worse than saying nothing.
 */
function buildHotels(row: OfferRow): RawCruiseHotel[] {
  const hotels: RawCruiseHotel[] = [];
  const add = (nights: number, name: string | null, city: string | null, stars: number | null, when: 'before' | 'after') => {
    if (nights > 0 && name && name.trim()) {
      hotels.push({ name: name.trim(), city: (city || '').trim(), nights, stars: stars ?? null, when });
    }
  };
  add(row.preHotelNights ?? 0, row.preHotelName, row.preHotelCity, row.preHotelStars, 'before');
  add(row.postHotelNights ?? 0, row.postHotelName, row.postHotelCity, row.postHotelStars, 'after');
  return hotels;
}

function cleanItinerary(raw: ItineraryEntry[]): RawCruiseItinerary[] {
  // Widgety records each port visit separately, so a single day visiting two
  // ports has multiple entries with the same dayNumber. Group by day and merge.
  const byDay = new Map<number, ItineraryEntry[]>();
  for (const entry of raw) {
    const day = entry.dayNumber;
    if (!byDay.has(day)) byDay.set(day, []);
    byDay.get(day)!.push(entry);
  }

  const result: RawCruiseItinerary[] = [];
  const sortedDays = [...byDay.keys()].sort((a, b) => a - b);

  for (let i = 0; i < sortedDays.length; i++) {
    const entries = byDay.get(sortedDays[i])!;
    const ports = [...new Set(entries.map(e => e.portName?.trim()).filter(Boolean) as string[])];
    const descEntry = entries.find(e => e.description?.trim());
    const description = descEntry ? stripHtml(descEntry.description) : '';
    const country = entries.find(e => e.country)?.country || '';
    if (ports.length === 0 && !description) continue;
    result.push({
      day: i + 1,
      port: ports.length > 0 ? ports.join(' / ') : 'Cruising',
      country,
      description,
    });
  }
  return result;
}

function parseDestination(raw: string | null): string {
  if (!raw) return '';
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed.join(' & ');
  } catch {
    // Not JSON, use as-is
  }
  return raw;
}

/** Map non-European cruise ports to their country for URL routing. */
const PORT_COUNTRY_MAP: Record<string, string> = {
  'Ho Chi Minh City': 'Vietnam',
  'Hanoi': 'Vietnam',
  'Ha Long Bay': 'Vietnam',
  'Siem Reap': 'Cambodia',
  'Phnom Penh': 'Cambodia',
  'Kampong Cham': 'Cambodia',
  'Angkor': 'Cambodia',
  'Tonle Sap': 'Cambodia',
  'Kasane': 'Botswana',
  'Victoria Falls': 'Zimbabwe',
  'Chobe National Park': 'Botswana',
};

function deriveCountry(
  itinerary: ItineraryEntry[],
  departurePort?: string,
  disembarkPort?: string,
): string {
  if (itinerary && itinerary.length > 0) {
    const counts = new Map<string, number>();
    for (const entry of itinerary) {
      if (entry.country) {
        const c = entry.country.trim();
        if (c) counts.set(c, (counts.get(c) || 0) + 1);
      }
    }
    if (counts.size > 0) {
      let maxCount = 0;
      let maxCountry = 'Europe';
      for (const [country, count] of counts) {
        if (count > maxCount) { maxCount = count; maxCountry = country; }
      }
      return maxCountry;
    }
  }
  if (departurePort && PORT_COUNTRY_MAP[departurePort]) return PORT_COUNTRY_MAP[departurePort];
  if (disembarkPort && PORT_COUNTRY_MAP[disembarkPort]) return PORT_COUNTRY_MAP[disembarkPort];
  return 'Europe';
}

function extractGalleryUrls(gallery: unknown): string[] {
  if (!Array.isArray(gallery)) return [];
  return gallery.map((img: unknown) => {
    if (typeof img === 'string') return img;
    if (img && typeof img === 'object' && 'url' in img) return (img as GalleryImage).url;
    return '';
  }).filter(Boolean);
}

function parseInclusions(raw: string | null): string[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed;
  } catch {
    // Not JSON
  }
  return [];
}

// ── Queries ─────────────────────────────────────────────────────────

interface OfferRow {
  offerId: number;
  offerTitle: string | null;
  cheapest: string | null;
  displayPrice: string | null;
  portFeePp: string | null;
  inclusions: string | null;
  preHotelNights: number | null;
  preHotelCity: string | null;
  preHotelName: string | null;
  preHotelStars: number | null;
  postHotelNights: number | null;
  postHotelCity: string | null;
  postHotelName: string | null;
  postHotelStars: number | null;
  routeTitle: string | null;
  routeSlug: string | null;
  description: string | null;
  destination: string | null;
  departurePort: string | null;
  disembarkPort: string | null;
  durationNights: number | null;
  featuredImage: string | null;
  itinerary: unknown;
  gallery: unknown;
  operatorName: string | null;
  /** The route's designated ship. Only a fallback; the ships that actually sail
   *  an offer come from its future sailings. */
  routeShipId: number | null;
}

/**
 * Operator is owned by the ROUTE (a route physically belongs to one operator).
 * The offer's operator_id is a stale denormalised copy and must NOT be used: it
 * caused the Zambezi A-ROSA/CroisiEurope mismatch.
 *
 * Do NOT join cruise_ships here to pull ship detail. Ship rows carry the whole
 * Widgety blob in raw_data, and joined per offer that is 18.9 MB down the wire
 * against 1.2 MB for everything else in this query. SHIP_DETAILS_SQL fetches
 * all 67 ships once instead; this carries the route's ship_id and looks it up.
 */
export const OFFERS_SQL = sql`
  SELECT
    co.id                    AS offerId,
    co.title                 AS offerTitle,
    co.cheapest_total_pp     AS cheapest,
    co.display_price         AS displayPrice,
    co.port_fee_pp           AS portFeePp,
    co.inclusions            AS inclusions,
    co.pre_hotel_nights      AS preHotelNights,
    co.pre_hotel_city_name   AS preHotelCity,
    co.pre_hotel_name        AS preHotelName,
    co.pre_hotel_star_rating AS preHotelStars,
    co.post_hotel_nights      AS postHotelNights,
    co.post_hotel_city_name   AS postHotelCity,
    co.post_hotel_name        AS postHotelName,
    co.post_hotel_star_rating AS postHotelStars,
    cr.title                 AS routeTitle,
    cr.slug                  AS routeSlug,
    cr.description           AS description,
    cr.destination           AS destination,
    cr.departure_port        AS departurePort,
    cr.disembark_port        AS disembarkPort,
    cr.duration_nights       AS durationNights,
    cr.featured_image        AS featuredImage,
    cr.itinerary             AS itinerary,
    cr.gallery               AS gallery,
    cop.name                 AS operatorName,
    cr.ship_id               AS routeShipId
  FROM cruise_offers co
  INNER JOIN cruise_routes cr ON co.route_id = cr.id
  INNER JOIN cruise_operators cop ON cr.operator_id = cop.id
  WHERE co.is_active = 1
`;

/**
 * The cheapest cabin on each sailing of each offer.
 *
 * The reduction is done here rather than in JS: the unaggregated join is about
 * 11k rows and this is about 2.8k. Ties resolve arbitrarily, exactly as the
 * first-wins loop this replaces did.
 */
export const SAILINGS_SQL = sql`
  SELECT offerId, sailingId, departureDate, returnDate, netCostPp, discountedCruisePp
  FROM (
    SELECT
      c.offer_id              AS offerId,
      c.sailing_id            AS sailingId,
      s.departure_date        AS departureDate,
      s.return_date           AS returnDate,
      CAST(c.net_cost_pp AS REAL)          AS netCostPp,
      CAST(c.discounted_cruise_pp AS REAL) AS discountedCruisePp,
      ROW_NUMBER() OVER (
        PARTITION BY c.offer_id, c.sailing_id
        ORDER BY CAST(c.net_cost_pp AS REAL)
      ) AS rn
    FROM cruise_offer_sailing_cabins c
    INNER JOIN cruise_sailings s ON c.sailing_id = s.id
    WHERE s.departure_date >= date('now')
      AND s.departure_date IS NOT NULL
      AND s.return_date IS NOT NULL
      AND CAST(c.net_cost_pp AS REAL) > 0
  )
  WHERE rn = 1
`;

/**
 * Which ships actually sail this offer, with each one's cheapest fare, earliest
 * date and row count. A route can run on several ships; about 43% do. The count
 * is of cabin rows, not sailings, matching what it replaces.
 */
export const OFFER_SHIPS_SQL = sql`
  SELECT
    c.offer_id                        AS offerId,
    s.ship_id                         AS shipId,
    MIN(CAST(c.net_cost_pp AS REAL))  AS cheapestNet,
    MIN(substr(s.departure_date, 1, 10)) AS firstDate,
    COUNT(*)                          AS sailingCount
  FROM cruise_offer_sailing_cabins c
  INNER JOIN cruise_sailings s ON c.sailing_id = s.id
  WHERE s.departure_date >= date('now')
    AND s.ship_id IS NOT NULL
    AND CAST(c.net_cost_pp AS REAL) > 0
  GROUP BY c.offer_id, s.ship_id
`;

export const SHIP_DETAILS_SQL = sql`
  SELECT id, name, description, cover_image_url AS coverImage, ship_class AS shipClass, raw_data AS rawData
  FROM cruise_ships
`;

// ── Build ───────────────────────────────────────────────────────────

export interface CatalogueRows {
  offerRows: OfferRow[];
  sailingRows: Array<{ offerId: number; sailingId: number; departureDate: string; returnDate: string; netCostPp: number; discountedCruisePp: number }>;
  offerShipRows: Array<{ offerId: number; shipId: number; cheapestNet: number; firstDate: string; sailingCount: number }>;
  shipRows: Array<{ id: number; name: string | null; description: string | null; coverImage: string | null; shipClass: string | null; rawData: unknown }>;
}

async function fetchRows(db: Database): Promise<CatalogueRows> {
  const [offerRows, sailingRows, offerShipRows, shipRows] = await Promise.all([
    db.all(OFFERS_SQL) as Promise<CatalogueRows['offerRows']>,
    db.all(SAILINGS_SQL) as Promise<CatalogueRows['sailingRows']>,
    db.all(OFFER_SHIPS_SQL) as Promise<CatalogueRows['offerShipRows']>,
    db.all(SHIP_DETAILS_SQL) as Promise<CatalogueRows['shipRows']>,
  ]);
  return { offerRows, sailingRows, offerShipRows, shipRows };
}

/**
 * Rows in, catalogue out. Pure, so it can be run against a dump of the real
 * tables and diffed against what the old export script produced.
 */
export function assembleCatalogue(
  { offerRows, sailingRows, offerShipRows, shipRows }: CatalogueRows,
): RawCruise[] {
  const shipDetailMap = new Map<number, ShipDetail>();
  for (const r of shipRows) {
    shipDetailMap.set(r.id, {
      name: r.name || '',
      description: r.description || '',
      coverImage: r.coverImage || '',
      class: r.shipClass || '',
      rawData: safeJsonParse(r.rawData) as ShipRawData | null,
    });
  }

  // offerId → date → the cheapest cabin on that date
  const sailingsByOffer = new Map<number, Map<string, { returnDate: string; cheapestNet: number; cabinPricePp: number }>>();
  for (const sr of sailingRows) {
    let byDate = sailingsByOffer.get(sr.offerId);
    if (!byDate) { byDate = new Map(); sailingsByOffer.set(sr.offerId, byDate); }
    const date = sr.departureDate.slice(0, 10);
    const existing = byDate.get(date);
    // Per date, the cheapest CABIN price wins, and that row's net becomes the
    // headline. Two sailings can share a date when a route runs twice.
    if (!existing || sr.discountedCruisePp < existing.cabinPricePp) {
      byDate.set(date, {
        returnDate: sr.returnDate.slice(0, 10),
        cheapestNet: sr.netCostPp,
        cabinPricePp: sr.discountedCruisePp,
      });
    }
  }

  const shipsByOffer = new Map<number, Array<{ shipId: number; cheapestNet: number; firstDate: string; sailingCount: number }>>();
  for (const r of offerShipRows) {
    const list = shipsByOffer.get(r.offerId) ?? [];
    list.push(r);
    shipsByOffer.set(r.offerId, list);
  }

  const built: RawCruise[] = [];

  for (const row of offerRows) {
    // Display-price override if set, otherwise auto-round down to a 9
    const overridePrice = row.displayPrice ? parseFloat(row.displayPrice) : 0;
    let price: number;
    if (overridePrice > 0) {
      price = overridePrice;
    } else {
      const rawPrice = row.cheapest ? parseFloat(row.cheapest) : 0;
      const floored = Math.floor(rawPrice);
      price = rawPrice > 0 ? floored - ((floored + 1) % 10) : 0;
    }
    if (price <= 0) continue; // nothing sellable

    const itinerary = (safeJsonParse(row.itinerary) as ItineraryEntry[]) || [];
    const galleryUrls = extractGalleryUrls(safeJsonParse(row.gallery));
    const featuredImage = row.featuredImage || (galleryUrls.length > 0 ? galleryUrls[0] : '');
    const country = deriveCountry(itinerary, row.departurePort || undefined, row.disembarkPort || undefined);
    const destination = parseDestination(row.destination);
    const title = (row.offerTitle && row.offerTitle.trim()) || row.routeTitle || 'Cruise';

    // Ships that actually sail it, cheapest first; the cheapest is the headline.
    let ships: RawCruiseShip[] = [];
    let ship: RawCruiseShip | null = null;
    const shipAgg = shipsByOffer.get(row.offerId);
    if (shipAgg && shipAgg.length > 0) {
      // Cheapest first, since the cheapest ship is the headline. Ties are
      // common and were previously broken by whatever order D1 returned rows:
      // six ships tie at £771 on offer 103 alone. That was frozen between
      // exports; on a live read it would pick a different hero ship every time
      // the cache refreshed. So: price, then whichever sails soonest, then id.
      ships = [...shipAgg]
        .sort((a, b) =>
          a.cheapestNet - b.cheapestNet
          || a.firstDate.localeCompare(b.firstDate)
          || a.shipId - b.shipId)
        .map(agg => {
          const detail = shipDetailMap.get(agg.shipId);
          return detail ? buildShipExport(agg.shipId, detail, agg.firstDate, agg.sailingCount) : null;
        })
        .filter((s): s is RawCruiseShip => s !== null);
      ship = ships[0] ?? null;
    }
    // Fallback: no sailing-derived ship (shouldn't happen) → the route's own.
    if (!ship && row.routeShipId != null) {
      const detail = shipDetailMap.get(row.routeShipId);
      if (detail) {
        ship = buildShipExport(row.routeShipId, detail);
        ships = [ship];
      }
    }

    const byDate = sailingsByOffer.get(row.offerId);
    const sailings = byDate
      ? [...byDate.entries()]
          .map(([date, s]) => ({
            date,
            returnDate: s.returnDate,
            pricePp: roundToNine(s.cheapestNet),
            cabinPricePp: Math.round(s.cabinPricePp * 100) / 100,
          }))
          .sort((a, b) => a.date.localeCompare(b.date))
      : [];

    // No future sailings means nothing to show
    if (sailings.length === 0) continue;

    built.push({
      id: row.offerId + ID_OFFSET,
      title,
      slug: row.routeSlug || '',
      price,
      destination,
      country,
      duration_nights: row.durationNights || 0,
      description: row.description || '',
      featured_image: featuredImage,
      gallery: galleryUrls,
      whats_included: parseInclusions(row.inclusions),
      itinerary: cleanItinerary(itinerary),
      operator_name: row.operatorName || '',
      ship_name: ship?.name || '',
      ship,
      ships,
      departure_port: row.departurePort || '',
      disembark_port: row.disembarkPort || '',
      board_basis: 'Full Board',
      port_fee_pp: parseFloat(row.portFeePp || '0'),
      hotels: buildHotels(row),
      sailings,
    });
  }

  // Several offers can share a route, and the route's slug is the URL. Keep the
  // one with the most sailings, cheaper price breaking a tie.
  const bySlug = new Map<string, RawCruise>();
  for (const entry of built) {
    const existing = bySlug.get(entry.slug);
    if (!existing
      || (entry.sailings?.length ?? 0) > (existing.sailings?.length ?? 0)
      || ((entry.sailings?.length ?? 0) === (existing.sailings?.length ?? 0) && entry.price < existing.price)) {
      bySlug.set(entry.slug, entry);
    }
  }

  // An offer with no operator or no price is a data fault, not something to
  // render. The export used to abort the whole run over one; a live read drops
  // the offending offer and serves the rest.
  return [...bySlug.values()].filter(e => {
    if (!(e.price > 0) || !e.operator_name) {
      console.error(`cruise catalogue: dropping offer ${e.id} "${e.slug}" (price ${e.price}, operator "${e.operator_name}")`);
      return false;
    }
    return true;
  });
}

async function buildCatalogue(db: Database): Promise<RawCruise[]> {
  return assembleCatalogue(await fetchRows(db));
}

// ── Cache ───────────────────────────────────────────────────────────

let cached: { at: number; data: RawCruise[] } | null = null;
let inflight: Promise<RawCruise[]> | null = null;

/**
 * The whole cruise catalogue. Memoised per isolate for TTL_MS, with concurrent
 * callers sharing one read so a cold isolate serving several requests at once
 * queries once.
 *
 * On a failed read a stale copy is served if we hold one: a minute-old price is
 * better than a 503. With nothing cached the error propagates, and the page
 * above decides what to do.
 */
export async function getCruiseCatalogue(db: Database): Promise<RawCruise[]> {
  const now = Date.now();
  if (cached && now - cached.at < TTL_MS) return cached.data;
  if (inflight) return inflight;

  inflight = buildCatalogue(db)
    .then(data => {
      cached = { at: Date.now(), data };
      return data;
    })
    .catch(err => {
      if (cached) {
        console.error('cruise catalogue refresh failed, serving stale', err);
        return cached.data;
      }
      throw err;
    })
    .finally(() => { inflight = null; });

  return inflight;
}
