// Read-only Drizzle schema for flight_packages + package_pricing
// Mirrors the admin API schema but only declares columns we need for SSR

import {
  pgTable,
  serial,
  text,
  real,
  integer,
  boolean,
  timestamp,
  jsonb,
  numeric,
} from 'drizzle-orm/pg-core';

export const flightPackages = pgTable('flight_packages', {
  id: serial('id').primaryKey().notNull(),
  title: text('title').notNull(),
  slug: text('slug').notNull(),
  category: text('category').notNull(),
  price: real('price').notNull(),
  currency: text('currency').default('GBP').notNull(),
  priceLabel: text('price_label').default('per adult').notNull(),
  description: text('description').notNull(),
  excerpt: text('excerpt'),
  whatsIncluded: jsonb('whats_included').default([]).notNull(),
  highlights: jsonb('highlights').default([]).notNull(),
  itinerary: jsonb('itinerary').default([]).notNull(),
  accommodations: jsonb('accommodations').default([]).notNull(),
  otherInfo: text('other_info'),
  featuredImage: text('featured_image'),
  gallery: jsonb('gallery').default([]),
  duration: text('duration'),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  isPublished: boolean('is_published').default(false).notNull(),
  displayOrder: integer('display_order').default(0).notNull(),
  createdAt: timestamp('created_at', { mode: 'string' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { mode: 'string' }).defaultNow().notNull(),
  sourceUrl: text('source_url'),
  tags: jsonb('tags').default([]).notNull(),
  videos: jsonb('videos').default([]).notNull(),
  singlePrice: real('single_price'),
  pricingDisplay: text('pricing_display').default('both').notNull(),
  excluded: text('excluded'),
  requirements: text('requirements'),
  attention: text('attention'),
  isSpecialOffer: boolean('is_special_offer').default(false).notNull(),
  countries: jsonb('countries').default([]).notNull(),
  pricingModule: text('pricing_module').default('manual').notNull(),
  flightApiSource: text('flight_api_source').default('european').notNull(),
  review: text('review'),
  autoRefreshEnabled: boolean('auto_refresh_enabled').default(false).notNull(),
  lastFlightRefreshAt: timestamp('last_flight_refresh_at', { mode: 'string' }),
  flightRefreshConfig: jsonb('flight_refresh_config'),
  isUnlisted: boolean('is_unlisted').default(false).notNull(),
  mobileHeroVideo: text('mobile_hero_video'),
  enabledHotelCategories: jsonb('enabled_hotel_categories').default([]),
  desktopHeroVideo: text('desktop_hero_video'),
  customExclusions: jsonb('custom_exclusions').default([]),
  boardBasisOverride: text('board_basis_override'),
  hotelOverride: text('hotel_override'),
  cityTaxConfig: jsonb('city_tax_config').default([]),
  additionalChargeName: text('additional_charge_name'),
  additionalChargeExchangeRate: numeric('additional_charge_exchange_rate', {
    precision: 16,
    scale: 10,
  }),
  additionalChargeCurrency: text('additional_charge_currency'),
  additionalChargeForeignAmount: numeric('additional_charge_foreign_amount', {
    precision: 10,
    scale: 2,
  }),
  cityTaxEnabled: boolean('city_tax_enabled').default(true).notNull(),
  includeAirlines: text('include_airlines'),
});

export const packagePricing = pgTable('package_pricing', {
  id: serial('id').primaryKey().notNull(),
  packageId: integer('package_id').notNull(),
  departureAirport: text('departure_airport').notNull(),
  departureAirportName: text('departure_airport_name').notNull(),
  departureDate: text('departure_date').notNull(),
  price: real('price').notNull(),
  currency: text('currency').default('GBP').notNull(),
  isAvailable: boolean('is_available').default(true).notNull(),
  createdAt: timestamp('created_at', { mode: 'string' }).defaultNow().notNull(),
});
