// Read-only Drizzle schema for flight_packages + package_pricing
// Mirrors the admin API schema but only declares columns we need for SSR

import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

export const flightPackages = sqliteTable('flight_packages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  title: text('title').notNull(),
  slug: text('slug').notNull(),
  category: text('category').notNull(),
  price: real('price').notNull(),
  currency: text('currency').default('GBP').notNull(),
  priceLabel: text('price_label').default('per adult').notNull(),
  description: text('description').notNull(),
  excerpt: text('excerpt'),
  whatsIncluded: text('whats_included', { mode: 'json' }).$type<string[]>().default([]).notNull(),
  highlights: text('highlights', { mode: 'json' }).$type<string[]>().default([]).notNull(),
  itinerary: text('itinerary', { mode: 'json' }).$type<unknown[]>().default([]).notNull(),
  accommodations: text('accommodations', { mode: 'json' }).$type<unknown[]>().default([]).notNull(),
  otherInfo: text('other_info'),
  featuredImage: text('featured_image'),
  gallery: text('gallery', { mode: 'json' }).$type<string[]>().default([]),
  duration: text('duration'),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  isPublished: integer('is_published', { mode: 'boolean' }).default(false).notNull(),
  displayOrder: integer('display_order').default(0).notNull(),
  createdAt: text('created_at').default(sql`(datetime('now'))`).notNull(),
  updatedAt: text('updated_at').default(sql`(datetime('now'))`).notNull(),
  sourceUrl: text('source_url'),
  tags: text('tags', { mode: 'json' }).$type<string[]>().default([]).notNull(),
  videos: text('videos', { mode: 'json' }).$type<string[]>().default([]).notNull(),
  singlePrice: real('single_price'),
  pricingDisplay: text('pricing_display').default('both').notNull(),
  excluded: text('excluded'),
  requirements: text('requirements'),
  attention: text('attention'),
  isSpecialOffer: integer('is_special_offer', { mode: 'boolean' }).default(false).notNull(),
  countries: text('countries', { mode: 'json' }).$type<string[]>().default([]).notNull(),
  pricingModule: text('pricing_module').default('manual').notNull(),
  flightApiSource: text('flight_api_source').default('european').notNull(),
  review: text('review'),
  autoRefreshEnabled: integer('auto_refresh_enabled', { mode: 'boolean' }).default(false).notNull(),
  lastFlightRefreshAt: text('last_flight_refresh_at'),
  flightRefreshConfig: text('flight_refresh_config', { mode: 'json' }),
  isUnlisted: integer('is_unlisted', { mode: 'boolean' }).default(false).notNull(),
  mobileHeroVideo: text('mobile_hero_video'),
  enabledHotelCategories: text('enabled_hotel_categories', { mode: 'json' }).$type<string[]>().default([]),
  desktopHeroVideo: text('desktop_hero_video'),
  customExclusions: text('custom_exclusions', { mode: 'json' }).$type<string[]>().default([]),
  boardBasisOverride: text('board_basis_override'),
  hotelOverride: text('hotel_override'),
  cityTaxConfig: text('city_tax_config', { mode: 'json' }).$type<unknown[]>().default([]),
  additionalChargeName: text('additional_charge_name'),
  additionalChargeExchangeRate: text('additional_charge_exchange_rate'),
  additionalChargeCurrency: text('additional_charge_currency'),
  additionalChargeForeignAmount: text('additional_charge_foreign_amount'),
  cityTaxEnabled: integer('city_tax_enabled', { mode: 'boolean' }).default(true).notNull(),
  includeAirlines: text('include_airlines'),
  displayPrice: real('display_price'),
  cities: text('cities', { mode: 'json' }).$type<string[]>().default([]).notNull(),
});

export const cruiseFlightPrices = sqliteTable('cruise_flight_prices', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  offerId: integer('offer_id').notNull(),
  sailingId: integer('sailing_id').notNull(),
  departureDate: text('departure_date').notNull(),
  returnDate: text('return_date').notNull(),
  airportCode: text('airport_code').notNull(),
  airportName: text('airport_name').notNull(),
  flightPricePp: text('flight_price_pp').notNull(),
  totalPricePp: text('total_price_pp').notNull(),
  source: text('source').notNull(),
  pricedAt: text('priced_at').default(sql`(datetime('now'))`).notNull(),
});

export const cruiseOffers = sqliteTable('cruise_offers', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  cheapestTotalPp: text('cheapest_total_pp'),
});

export const packagePricing = sqliteTable('package_pricing', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  packageId: integer('package_id').notNull(),
  departureAirport: text('departure_airport').notNull(),
  departureAirportName: text('departure_airport_name').notNull(),
  departureDate: text('departure_date').notNull(),
  price: real('price').notNull(),
  currency: text('currency').default('GBP').notNull(),
  isAvailable: integer('is_available', { mode: 'boolean' }).default(true).notNull(),
  createdAt: text('created_at').default(sql`(datetime('now'))`).notNull(),
});
