name = "holiday-site"
pages_build_output_dir = "dist/"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "holiday-flights-db"
database_id = "fd1870e7-9ad7-45a3-97fc-71f904189066"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "holidays-images"

[vars]
PRIVYR_WEBHOOK_URL = "https://www.privyr.com/api/v1/incoming-leads/0vZfjMQw/b7XVsZZO"
